### ISSUE TITLE
Cloudshell timeout deployment

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/AppMigrationWorkshop#5]
## Expected Behavior
Cloud shell should deploy all resources

## Current Behavior
Cloud shell session times out after 2 mins into the deployment. Deployment is still running

VERBOSE: 4:58:15 AM - Create template deployment 'azuredeploy-0313-0458'...

....[OMITTED]

VERBOSE: 4:59:37 AM - Resource Microsoft.Compute/virtualMachines 'apmqy63-jmp' provisioning status is running
VERBOSE: 4:59:37 AM - Resource Microsoft.Resources/deployments 'qy63jx2j7y4cy-apmqy63-jmpnicDeployment' provisioning status is succeeded
VERBOSE: 4:59:37 AM - Checking deployment status in 5 seconds
VERBOSE: 4:59:50 AM - Resource Microsoft.Sql/servers/databases 'apmqy63jx2j7y4cy-sqlsvr/TIMETRACKERDB' provisioning status is succeeded
VERBOSE: 4:59:50 AM - Resource Microsoft.Sql/servers/databases 'apmqy63jx2j7y4cy-sqlsvr/CLASSIFIEDSDB' provisioning status is succeeded
VERBOSE: 4:59:50 AM - Checking deployment status in 5 seconds
New-AzureRmResourceGroupDeployment : A task was canceled.
At C:\users\ContainerAdministrator\CloudDrive\AppMigrationWorkshopRepo\AppMigrationWorkshop\Shared\ARM-NewIaaS\Deploy-AzureResourceGroup.ps1:108 char:5
+     New-AzureRmResourceGroupDeployment -Name ((Get-ChildItem $Templat ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], TaskCanceledException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

Template deployment returned the following errors:
A task was canceled.

## Possible Solution
Increase the timeout

## Steps to Reproduce (for bugs)
Deploy HOL 1
Wait

## Context
In the Cloudshell using PowerShell

**Comment by paulomarquesc** [comment]
This issue could not be reproduced with the current version of the template, deploying from Windows PowerShell or from CloudShell.
CloudShell will time out itself and user will have to reconned after 20 minutes, for this, an extra lab exercise was created in order to teach the users how to monitor their deployments from the portal.

[HOL 01 - Exercise 4: Monitoring your deployment](https://github.com/AzureCAT-GSI/AppMigrationWorkshop/tree/develop/HOL/01-setup#ex4)
