### ISSUE TITLE
HOL 2 - RSAT tools are missing on Jumpbox build 1709

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/AppMigrationWorkshop#6]
## Expected Behavior
After installing the RSAT tools, the DNS tools exist

## Current Behavior
PS C:\Users\appmigadmin>  Add-DnsServerResourceRecordA
Add-DnsServerResourceRecordA : The term 'Add-DnsServerResourceRecordA' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:2
+  Add-DnsServerResourceRecordA
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-DnsServerResourceRecordA:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

## Possible Solution
Install the RSAT tools manually per  https://support.microsoft.com/en-us/help/4055558/rsat-missing-dns-server-tool-in-windows-10-version-1709

## Steps to Reproduce (for bugs)
Run HOL 2

## Context
Unable to continue until you install or remote into the DC and run the scripts from there

## Your Environment
Jumpbox

**Comment by paulomarquesc** [comment]
Performed a new deployment of the lab and this issue was not reproduced while executing it.
