### ISSUE TITLE
HOL2 - Admistrator is locked out of SQL and cannot create DBs

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/AppMigrationWorkshop#7]
## Expected Behavior
When restoring DBs, the admin is able to restore databases

## Current Behavior
Not able to restore databases, Access denied

Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

PS C:\Users\appmigadmin> SQLCMD -E -S $($ENV:COMPUTERNAME) -Q "RESTORE DATABASE [TimeTracker] FROM DISK='C:\Databases\ti
metracker.bak' WITH MOVE 'tempname' TO 'C:\Databases\timetracker.mdf', MOVE 'TimeTracker_Log' TO 'C:\Databases\timetrack
er_log.ldf'"
Msg 262, Level 14, State 1, Server APMQY63-SQL, Line 1
CREATE DATABASE permission denied in database 'master'.
Msg 3013, Level 16, State 1, Server APMQY63-SQL, Line 1
RESTORE DATABASE is terminating abnormally.
PS C:\Users\appmigadmin>     SQLCMD -E -S $($ENV:COMPUTERNAME) -Q "RESTORE DATABASE [Classifieds] FROM DISK='C:\Database
s\classifieds.bak' WITH MOVE 'Database' TO 'C:\Databases\classifieds.mdf', MOVE 'Database_log' TO 'C:\Databases\classifi
eds_log.ldf'"
Msg 262, Level 14, State 1, Server APMQY63-SQL, Line 1
CREATE DATABASE permission denied in database 'master'.
Msg 3013, Level 16, State 1, Server APMQY63-SQL, Line 1
RESTORE DATABASE is terminating abnormally.
PS C:\Users\appmigadmin>     SQLCMD -E -S $($ENV:COMPUTERNAME) -Q "RESTORE DATABASE [Jobs] FROM DISK='C:\Databases\jobs.
bak' WITH MOVE 'EmptyDatabase' TO 'C:\Databases\jobs.mdf', MOVE 'EmptyDatabase_log' TO 'C:\Databases\jobs_log.ldf'"
Msg 262, Level 14, State 1, Server APMQY63-SQL, Line 1
CREATE DATABASE permission denied in database 'master'.
Msg 3013, Level 16, State 1, Server APMQY63-SQL, Line 1
RESTORE DATABASE is terminating abnormally.
PS C:\Users\appmigadmin>

## Possible Solution
Ensure the admin account is SA

**Comment by paulomarquesc** [comment]
This is also related to [issue #9](https://github.com/AzureCAT-GSI/AppMigrationWorkshop/issues/9)
