### ISSUE TITLE
HOL2 - Connection strings for Web Apps are invalid

### ISSUE THREAD

**Issue by ivegamsft** [AzureCAT-GSI/AppMigrationWorkshop#8]
## Expected Behavior
The web apps have the correct connection string set for the DB

## Current Behavior
Connectstrings point to SQL Express locally

## Possible Solution
Update web.config for the source apps to point to the SQL DB

**Comment by paulomarquesc** [comment]
Fixed all connection strings, the ZIP files containing the Apps now all have the correct Web.config with a string <sqlServerName> that must be replaced by the real SQL server name and this is mentioned during the lab.
